version: '3.8'

services:
  nexrad-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEBUG=false
      - PORT=5000
    volumes:
      - ./processed_data:/app/processed_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro  # Optional: for HTTPS
    depends_on:
      - nexrad-api
    restart: unless-stopped

volumes:
  processed_data: